global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@statex.cz'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://statex-monitoring-service:8000/api/alerts'

- name: 'critical-alerts'
  email_configs:
  - to: 'admin@statex.cz'
      subject: '[CRITICAL] StateX Alert: {{ .GroupLabels.alertname }}'
      body: |
        {{ range .Alerts }}
        Alert: {{ .Annotations.summary }}
        Description: {{ .Annotations.description }}
        {{ end }}

- name: 'warning-alerts'
  email_configs:
  - to: 'admin@statex.cz'
      subject: '[WARNING] StateX Alert: {{ .GroupLabels.alertname }}'
      body: |
        {{ range .Alerts }}
        Alert: {{ .Annotations.summary }}
        Description: {{ .Annotations.description }}
        {{ end }}
