global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'user-portal'
    static_configs:
      - targets: ['user-portal:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'submission-service'
    static_configs:
      - targets: ['submission-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'ai-orchestrator'
    static_configs:
      - targets: ['ai-orchestrator:8003']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'ai-workers'
    static_configs:
      - targets: ['ai-workers:8004']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8005']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'content-service'
    static_configs:
      - targets: ['content-service:8006']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'logging-service'
    static_configs:
      - targets: ['logging-service:8007']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 30s

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    scrape_interval: 30s
