services:
  notification-service:
    build: .
    container_name: ${NOTIFICATION_SERVICE_CONTAINER_NAME:-statex_notification_dev}
    ports:
      - "${NOTIFICATION_SERVICE_EXTERNAL_PORT:-8005}:${NOTIFICATION_SERVICE_INTERNAL_PORT:-8005}"
    environment:
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN}
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
    env_file:
      - ../.env
    restart: unless-stopped
    networks:
      - statex_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${NOTIFICATION_SERVICE_INTERNAL_PORT:-8005}/health"]
      interval: 20s
      timeout: 10s
      retries: 2
      start_period: 30s

networks:
  statex_network:
    external: true
