services:
  # API Gateway - Central routing for all services
  api-gateway:
    image: nginx:alpine
    container_name: statex_api_gateway_dev
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ../statex-infrastructure/nginx/api-gateway.conf:/etc/nginx/conf.d/default.conf:ro
      - ../statex-infrastructure/nginx/ssl-dev:/etc/nginx/ssl:ro
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST:-localhost}
      - DEFAULT_HOST=${DEFAULT_HOST:-localhost}
    networks:
      - statex_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 20s
      timeout: 10s
      retries: 2
      start_period: 10s

  # Platform Management Service - Central orchestration hub
  platform-management:
    image: python:3.11-slim
    container_name: statex_platform_management_dev
    volumes:
      - ./services/platform-management:/app
      - ~/.cache/pip:/root/.cache/pip
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://statex:statex_password@host.docker.internal:5432/statex
      - REDIS_URL=redis://host.docker.internal:6379
      - RABBITMQ_URL=amqp://statex:statex_password@host.docker.internal:5672
      
      # Service URLs
      - AI_ORCHESTRATOR_URL=http://host.docker.internal:8010
      - NOTIFICATION_SERVICE_URL=http://host.docker.internal:8005
      - SUBMISSION_SERVICE_URL=http://host.docker.internal:8002
      - USER_PORTAL_URL=http://host.docker.internal:8006
      - CONTENT_SERVICE_URL=http://host.docker.internal:8009
      - MONITORING_SERVICE_URL=http://host.docker.internal:8007
      - LOGGING_SERVICE_URL=http://host.docker.internal:8008
      
      # Development Settings
      - DEBUG=true
      - LOG_LEVEL=debug
      - ENVIRONMENT=development
    networks:
      - statex_network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  statex_network:
    external: true
