global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@statex.cz'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://statex-monitoring-service:8000/api/alerts'

- name: 'default-email'
  email_configs:
  - to: 'admin@statex.cz'
