apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: statex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: statex-platform
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
          name: prometheus
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        - name: prometheus-data
          mountPath: /prometheus
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: statex
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: statex
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    rule_files:
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'statex-platform'
      static_configs:
      - targets: ['statex-platform.statex.svc.cluster.local:8000']
    - job_name: 'statex-ai'
      static_configs:
      - targets: ['statex-ai.statex.svc.cluster.local:8010']
    - job_name: 'statex-notification'
      static_configs:
      - targets: ['statex-notification.statex.svc.cluster.local:8005']
    - job_name: 'statex-website'
      static_configs:
      - targets: ['statex-website.statex.svc.cluster.local:3000']
    - job_name: 'kubernetes-nodes'
      static_configs:
      - targets: ['kubernetes.default.svc.cluster.local:443']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: statex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      serviceAccountName: statex-platform
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3002
          name: grafana
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: statex-secrets
              key: GRAFANA_PASSWORD
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: statex
spec:
  selector:
    app: grafana
  ports:
  - port: 3002
    targetPort: 3002
  type: ClusterIP
