apiVersion: apps/v1
kind: Deployment
metadata:
  name: statex-platform
  namespace: statex
spec:
  replicas: 3
  selector:
    matchLabels:
      app: statex-platform
  template:
    metadata:
      labels:
        app: statex-platform
    spec:
      serviceAccountName: statex-platform
      containers:
      - name: platform
        image: statex/platform:latest
        ports:
        - containerPort: 8000
          name: platform
        - containerPort: 8001
          name: api-gateway
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: statex-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: statex-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: statex-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: statex-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: statex-secrets
              key: DB_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: statex-config
              key: REDIS_HOST
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: statex-secrets
              key: REDIS_PASSWORD
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: statex-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: statex-secrets
              key: RABBITMQ_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: statex-secrets
              key: JWT_SECRET
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: statex-config
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: statex-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: statex-platform
  namespace: statex
spec:
  selector:
    app: statex-platform
  ports:
  - port: 8000
    targetPort: 8000
    name: platform
  - port: 8001
    targetPort: 8001
    name: api-gateway
  type: ClusterIP
