apiVersion: apps/v1
kind: Deployment
metadata:
  name: statex-notification
  namespace: statex
spec:
  replicas: 2
  selector:
    matchLabels:
      app: statex-notification
  template:
    metadata:
      labels:
        app: statex-notification
    spec:
      serviceAccountName: statex-platform
      containers:
      - name: notification-service
        image: statex/notification-service:latest
        ports:
        - containerPort: 8005
          name: notifications
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: statex-config
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: statex-secrets
              key: DB_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: statex-config
              key: REDIS_HOST
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: statex-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: statex-secrets
              key: RABBITMQ_PASSWORD
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: statex-secrets
              key: SMTP_PASSWORD
        - name: PLATFORM_URL
          valueFrom:
            configMapKeyRef:
              name: statex-config
              key: PLATFORM_URL
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: statex-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: statex-notification
  namespace: statex
spec:
  selector:
    app: statex-notification
  ports:
  - port: 8005
    targetPort: 8005
    name: notifications
  type: ClusterIP
